"""init

Revision ID: 730341582222
Revises: ce69b60e3896
Create Date: 2025-12-06 10:39:06.921561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730341582222'
down_revision: Union[str, Sequence[str], None] = 'ce69b60e3896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_requests_user_id_key'), 'chat_requests', type_='unique')
    op.drop_constraint(op.f('chat_requests_user_id_fkey'), 'chat_requests', type_='foreignkey')
    op.create_foreign_key(None, 'chat_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_requests', type_='foreignkey')
    op.create_foreign_key(op.f('chat_requests_user_id_fkey'), 'chat_requests', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('chat_requests_user_id_key'), 'chat_requests', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
